name: Check Version update on release

on:
  pull_request:
    branches:
      - 'release/*'

defaults:
  run:
    shell: bash -o pipefail {0}

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - run: |
          CHANGED_FILES=$(git diff --name-only "origin/${{ github.base_ref }}...HEAD")

          if ! echo "${CHANGED_FILES}" | grep -qx "package.json"; then
            echo "::error::Release PRs must include an update to package.json."
            exit 1
          fi

          if ! echo "${CHANGED_FILES}" | grep -qx "package-lock.json"; then
            echo "::error::Release PRs must include an update to package-lock.json."
            exit 1
          fi
