name: Test & Publish

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main

jobs:
  audit:
    name: Audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version-file: '/.nvmrc'

      - run: npm audit

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version-file: '/.nvmrc'

      - run: npm ci
      - run: npm run lint --if-present

  build:
    name: Build
    runs-on: ubuntu-latest
    needs:
      - audit
      - lint
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version-file: '/.nvmrc'

      - run: npm ci
      - run: npm run build

  test:
    name: Test
    runs-on: ${{ matrix.os }}
    needs:
      - build
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version-file: '/.nvmrc'

      - run: npm ci
      - run: npm test -- --coverage

      - name: Upload coverage artifact
        if: always() && matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage

  publish:
    name: Publish
    needs:
      - test
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/'))
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version-file: '/.nvmrc'
          registry-url: 'https://registry.npmjs.org'

      - run: npm ci
      - run: npm run build

      - name: Publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          # skip publish if package is marked as private
          if [ "$(node -e \"process.stdout.write(require('./package.json').private ? 'true' : 'false')\")" = "true" ]; then
            echo "package.json.private = true. Skipping publish."
            exit 0
          fi
          npm publish --provenance --access public
