name: Test & Publish

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  audit:
    name: Audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version-file: '/.nvmrc'

      - run: npm audit

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version-file: '/.nvmrc'

      - run: npm ci
      - run: npm run lint --if-present

  build:
    name: Build
    runs-on: ubuntu-latest
    needs:
      - audit
      - lint
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version-file: '/.nvmrc'

      - run: npm ci
      - run: npm run build

  test:
    name: Test
    runs-on: ${{ matrix.os }}
    needs:
      - build
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version-file: '/.nvmrc'

      - run: npm ci
      - run: npm test -- --coverage

      - name: Upload coverage artifact
        if: always() && matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage

  publish:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    name: Publish on version update
    needs:
      - test
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version-file: '/.nvmrc'
          registry-url: 'https://registry.npmjs.org'

      - name: Check for version update
        id: check_version
        run: |
          CURRENT_VERSION=$(jq -r .version package.json)
          PREVIOUS_VERSION=$(git show HEAD~1:package.json | jq -r .version)

          if [[ "$CURRENT_VERSION" != "$PREVIOUS_VERSION" ]]; then
            echo "version_updated=true" >> $GITHUB_OUTPUT
          fi

      - if: steps.check_version.outputs.version_updated
        run: npm ci

      - if: steps.check_version.outputs.version_updated
        run: npm run build

      - if: steps.check_version.outputs.version_updated
        name: Publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm publish --provenance --access public
