name: Test & Publish

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

defaults:
  run:
    shell: bash -o pipefail {0}

jobs:
  audit:
    name: Audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version-file: '/.nvmrc'

      - run: npm audit

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version-file: '/.nvmrc'

      - run: npm ci
      - run: npm run lint --if-present

  build:
    name: Build
    runs-on: ubuntu-latest
    needs:
      - audit
      - lint
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version-file: '/.nvmrc'

      - run: npm ci
      - run: npm run build

  test:
    name: Test
    runs-on: ${{ matrix.os }}
    needs:
      - build
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version-file: '/.nvmrc'

      - run: npm ci
      - run: npm test -- --coverage

      - name: Upload coverage artifact
        if: always() && matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage

  detect_version_update:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    name: Detect version update
    runs-on: ubuntu-latest
    outputs:
      detected: ${{ steps.detect.outputs.detected }}
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 2

      - id: detect
        run: |
          CURRENT_VERSION=$(jq -r .version package.json)
          PREVIOUS_VERSION=$(git show HEAD~1:package.json | jq -r .version)

          if [[ "$CURRENT_VERSION" != "$PREVIOUS_VERSION" ]]; then
            echo "::notice file=package.json,line=3::Version has been updated. Proceeding to publish."
            echo "detected=true" >> $GITHUB_OUTPUT
          else
            echo "::notice::Version has not changed. Skipping publish."
            echo "detected=false" >> $GITHUB_OUTPUT
          fi

  publish:
    name: Publish
    needs:
      - test
      - detect_version_update
    if: needs.detect_version_update.outputs.detected == 'true'
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version-file: '/.nvmrc'
          registry-url: 'https://registry.npmjs.org'

      - run: npm ci
      - run: npm run build

      - name: Publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm publish --provenance --access public
